feat: updated figma links in issue template
layer5io/mesheryctl-aliases pull request #11
Opened 2023-08-01 18:10 UTC by abhijeetgauravm

**Description**
Updated figma links in issue template.
This PR fixes #10 

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

2023-08-19 15:09 UTC, thisiskaransgit requested changes

2023-08-19 15:09 UTC, thisiskaransgit commented on .github/ISSUE_TEMPLATE/bug_report.md
> +- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9
```suggestion
```

2023-08-19 15:09 UTC, thisiskaransgit approved these changes
Looks good to merge @abhijeetgauravm , thank you for your contribution :tada:

2023-08-19 15:53 UTC, thisiskaransgit approved these changes
Looks good to merge, thank you for your contribution :tada:

2023-08-22 09:13 UTC, leecalcote commented
Thanks!

2023-08-22 09:13 UTC, merged